# --- three different dash is need to discover the different profiles

spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8082

---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8080